/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Version of the BentoBox core library. */
export declare function version(): string
/** Whether kernel sandboxing is available on this platform. */
export declare function sandboxSupported(): boolean
/**
 * Explain why `path` (file or tcp:/udp: address) would be blocked by the
 * sandbox rules for `worktree_path`.
 */
export declare function sandboxWhy(path: string, worktreePath: string, blockNetwork: boolean): string
/** Compress content through the BentoBox smart crusher. */
export declare function compress(content: string): string
/**
 * Check policy JSON `{"permissions": [...]}` against required permission JSON.
 * Returns true if allowed, false if denied.
 */
export declare function runtimeCheckPermission(policyJson: string, requiredJson: string): boolean
/**
 * Check a command string against the dangerous-command blocklist.
 * Returns true if allowed, false if blocked.
 */
export declare function runtimeCheckCommand(cmd: string): boolean
/**
 * Snapshot `workdir` into `snapshot_dir`, excluding dirs in the JSON array.
 * Returns the number of files snapshotted.
 */
export declare function runtimeSnapshot(workdir: string, snapshotDir: string, excludeJson?: string | undefined | null): number
/**
 * Restore files from `snapshot_dir` back into `workdir`.
 * Returns the number of files restored.
 */
export declare function runtimeRestore(workdir: string, snapshotDir: string): number
/**
 * Validate compartment configs JSON `{"configs": [...]}` and edges JSON
 * `[["a", "b"]]`. Returns true if valid, false if invalid (matches Go).
 */
export declare function runtimeValidate(configsJson: string, edgesJson: string): boolean
/**
 * Check if a message `from` to `to` is permitted by the configs JSON.
 * Returns true if allowed, false if denied; throws if a compartment is unknown.
 */
export declare function runtimeCanRoute(configsJson: string, from: string, to: string): boolean
/**
 * Match a request path against credential routes JSON; on a match, return
 * the rewritten upstream URL, or null if no route matched.
 */
export declare function runtimeCredentialRewrite(routesJson: string, path: string): string | null
/** Resolve a credential source like `env:OPENAI_API_KEY`. */
export declare function runtimeCredentialResolve(source: string): string
/**
 * Opaque, pre-built compartment runtime. Parses configs once so hot-path
 * `canRoute`/`runOrder` calls do not re-parse JSON. Not thread-safe.
 */
export declare class Runtime {
  /**
   * Build a Runtime from configs JSON `{"configs": [...]}` and edges JSON.
   * Throws if a compartment or edge is invalid.
   */
  constructor(configsJson: string, edgesJson: string)
  /**
   * Check if a message `from` to `to` is permitted.
   * Returns true if allowed, false if denied; throws if a compartment is unknown.
   */
  canRoute(from: string, to: string): boolean
  /**
   * Execution order as compartment names, optionally starting at `entry`
   * (omit to run from the start).
   */
  runOrder(entry?: string | undefined | null): Array<string>
  /** Registered compartment names, in registration order. */
  names(): Array<string>
}
